---
- hosts: all
  become: true
  vars_files: secret.yaml 
  vars:
    default_container_name: simple-app
    default_container_image: "35.209.45.241:8085/simple-app:27"
    registry_url: "35.209.45.241:8085"
  tasks:
    - name: Login to Nexus Repository
      docker_login:
        registry_url: "{{ registry_url }}"
        username: "admin"
        passowrd: "{{password}}"

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: present