---
###every yaml start with three dash
- 
  #target where our play is going to run 
  hosts: client
  become: yes
  vars:
    tomcat_download_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.tar.gz
    tomcat_download_location: /usr/share/tomcat/apache-tomcat-9.0.70.tar.gz
  ##define list of task that we are executing

  tasks:
    - name: update my endpoint and install openjdk
      ansible.builtin.apt:
        name: default-jdk
        state: latest
        update_cache: yes
    - name: create a tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: Add the user tomcat 
      ansible.builtin.user:
        name: tomcat 
        group: tomcat 
    - name: create tomcat directory
      file:
        path: /usr/share/tomcat 
        state: directory 
        owner: tomcat 
        group: tomcat 
    - name: Download Tomcat 
      get_url:
        url: "{{tomcat_download_url}}"
        dest: "{{tomcat_download_location}}"
    - name: unarchive the tomcat 
      unarchive:
        src: "{{tomcat_download_location}}"
        dest: /usr/share/tomcat
        remote_src: yes 
        extra_opts: [--strip-components=1]
        owner: tomcat 
        group: tomcat 
        creates: /usr/share/tomcat/bin 
    - name: copy the tomcat service 
      template:
        src: templates/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      when: ansible_service_mgr == 'systemd'
    - name: start and enable tomcat 
      service:
        daemon_reload: yes 
        name: tomcat 
        state: started 
        enabled: yes 
      when: ansible_service_mgr == 'systemd' 
    - name: Download Tomcat 
      get_url:
        url_username: "admin"
        url_password: "Kislaya@12345"
        url: "http://20.169.185.165:8081/repository/maven-snapshots/websocket-demo/websocket-demo/0.0.1-SNAPSHOT/websocket-demo-0.0.1-20230106.115039-6.jar"
        dest: "/usr/share/tomcat/webapps"
    